Repository 1-n-Fee/1-n-Web-Frontend, pull requests merged in 2022-07, with the labels that each got.

#1 [1/ n - 24 ] 회원가입 페이지 관련 기능 구현
  src/component/signup/GenderRadioBtn.jsx
  src/component/signup/IdInput.jsx
  src/component/signup/MajorSelect.jsx
  src/component/signup/NameInput.jsx
  src/component/signup/NickNameInput.jsx
  src/component/signup/PhoneNumInput.jsx
  src/component/signup/PwDupInput.jsx
  src/component/signup/PwInput.jsx
  src/component/signup/SignUpInputs.jsx
  src/pages/SignUpPage.jsx
Labels: ✨feature

#3 [1/n - 44] 회원 가입 라우터 추가
  package-lock.json
  package.json
  src/App.js
  src/routes/Router.jsx
Labels: ✨feature

#4 [1/n - 57] Header 컴포넌트 관련 기능 구현
  src/component/Header/AlarmMenu.jsx
  src/component/Header/Alarms/ChatCreatedAlarm.jsx
  src/component/Header/Alarms/JoinRequestAlarm.jsx
  src/component/Header/Alarms/JoinResponseAlarm.jsx
  src/component/Header/Header.jsx
  src/component/Header/Icon.jsx
  src/component/Header/Icons.jsx
  src/component/Header/MyPageMenu.jsx
  src/component/common/AlarmDelBtn.jsx
  src/component/common/SearchBar.jsx
  src/component/common/Tag.jsx
  src/routes/Router.jsx
Labels: ✨feature

#6 [1/n - 64 ] home 페이지 및 컴포넌트 파일 구조 수정
  src/component/home/home.module.css
  src/component/home/map.jsx
  src/component/home/meal_detail.jsx
  src/component/home/meal_detail.module.css
  src/component/home/meal_item.jsx
  src/component/home/meal_list.jsx
  src/component/home/meal_list.module.css
  src/component/home/sideBar.jsx
  src/component/home/sideBar.module.css
  src/pages/home.jsx
Labels: ♻️ refactor

#11 [1/n - ???] PR 템플릿 추가
  .github/PULL_REQUEST_TEMP.md
  README.md
Labels: 📝 docs

#12 [1/n - ? ] 채팅 페이지 UI 구현
  src/component/chat/ChatRoom.jsx
  src/component/chat/ChatRoomHeader.jsx
  src/component/chat/ChatRoomInfoDiv.jsx
  src/component/chat/ChatRoomsInfo.jsx
  src/component/chat/ChatStateTag.jsx
  src/component/chat/ChattingInput.jsx
  src/component/common/StateTag.jsx
  src/pages/chat/ChatPage.jsx
  src/routes/Router.jsx
Labels: ✨feature

#14 [1/n] Revert "[1/n] bug issue template, custom issue template 추가 "
  .github/ISSUE_TEMPLATE/bug-issue-template.md
  .github/ISSUE_TEMPLATE/custom-issue-template.md
  .github/ISSUE_TEMPLATE/custom.md
Labels: 🐛 bug

#15 [1/n] bug issue template, custom issue template 추가
  .github/ISSUE_TEMPLATE/bug-issue-template.md
  .github/ISSUE_TEMPLATE/custom-issue-template.md
Labels: 📝 docs

#19 [1/n - 1] PR template 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📝 docs

#23 [1/n - 5] custom template의 항목 제목 변경
  .github/ISSUE_TEMPLATE/custom-issue-template.md
Labels: 📝 docs

#25 [1/n - 4] Header 컴포넌트 스타일 수정
  src/App.js
  src/component/Header/AlarmMenu.jsx
  src/component/Header/Alarms/ChatCreatedAlarm.jsx
  src/component/Header/Alarms/JoinRequestAlarm.jsx
  src/component/Header/Alarms/JoinResponseAlarm.jsx
  src/component/Header/Header.jsx
  src/component/Header/Icon.jsx
  src/component/Header/Icons.jsx
  src/component/Header/MyPageMenu.jsx
  src/component/common/AlarmDelBtn.jsx
  src/component/common/SearchBar.jsx
  src/component/common/Tag.jsx
  src/component/style/AlarmSubInfoStyle.jsx
  src/component/style/AlarmWrapperStyle.jsx
  src/component/style/GlobalStyles.jsx
Labels: ✨feature, 🎨 style

#27 [1/n - 6] home("/") 경로 외에도 검색창이 보이는 오류 해결
  src/component/Header/Header.jsx
Labels: 🐛 bug

#29 [1/n - 7] main branch의 template을 develop branch로 가져오기
  .github/ISSUE_TEMPLATE/bug-issue-template.md
  .github/ISSUE_TEMPLATE/custom-issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: 📝 docs

#32 [1/n - 9] home("/") 경로 이외에서 헤더가 다른 컴포넌트랑 겹치는 문제 해결
  src/component/Header/Header.jsx
Labels: 🐛 bug

#36 [1/n-2] 로그인 페이지 구현
  public/kakao_btn.png
  src/component/login/idInput.jsx
  src/component/login/kakaoButton.jsx
  src/component/login/loginButton.jsx
  src/component/login/loginForm.jsx
  src/component/login/pwInput.jsx
  src/pages/loginPage.jsx
  src/routes/Router.jsx
Labels: ✨feature, 🎨 style

#37 [1/n - 3] 아이디/비밀번호 찾기 페이지 구현
  src/component/find/findIdForm.jsx
  src/component/find/findPwForm.jsx
  src/component/login/loginForm.jsx
  src/component/style/findFormStyle.jsx
  src/component/style/findPageStyle.jsx
  src/pages/findIdPage.jsx
  src/pages/findPwPage.jsx
  src/routes/Router.jsx
Labels: ✨feature, 🎨 style

#40 [1/n - 10] 채팅 페이지 스타일 수정
  src/component/chat/ChatRoom.jsx
  src/component/chat/ChatRoomHeader.jsx
  src/component/chat/ChatRoomInfoDiv.jsx
  src/component/chat/ChatRoomsInfo.jsx
  src/component/chat/ChattingInput.jsx
  src/component/common/StateTag.jsx
  src/component/style/DropDownListStyle.jsx
  src/component/style/DropDownWrapperStyle.jsx
  src/component/style/GlobalStyles.jsx
  src/pages/chat/ChatPage.jsx
Labels: 🎨 style

#42 [1\n - 14] 회원정보 조회/변경 페이지 구현
  babel-plugin-macros.config.js
  babel.config.js
  package-lock.json
  package.json
  src/component/pwChange/dupPwInput.jsx
  src/component/pwChange/newPwInput.jsx
  src/component/signup/GenderRadioBtn.jsx
  src/component/signup/SignUpInputs.jsx
  src/component/userInfo/accordionLayout.jsx
  src/component/userInfo/userInfoAccordion.jsx
  src/pages/nNameChange.jsx
  src/pages/pwChange.jsx
  src/pages/userInfo.jsx
  src/routes/Router.jsx
Labels: ✨feature
