Repository 1-n-Fee/1-n-Web-Frontend, pull requests merged in 2022-08, with the labels that each got.

#44 [1/n - 16] 히스토리 페이지 구현
  package-lock.json
  package.json
  src/component/Header/MyPageMenu.jsx
  src/component/common/UserStateTag.jsx
  src/component/history/HistoryDetailInfoTab.jsx
  src/component/history/HistoryListContainer.jsx
  src/component/history/HistoryListHeader.jsx
  src/component/history/HistoryOrderList.jsx
  src/component/history/HistoryPartyList.jsx
  src/component/history/HistoryPopup.jsx
  src/component/history/HistoryTab.jsx
  src/component/history/RequestStateTag.jsx
  src/index.js
  src/pages/HistoryPage.jsx
  src/recoil/historyData/atom.js
  src/routes/Router.jsx
Labels: ✨feature

#46 [1/n - 17] 사업자 회원가입 페이지 구현
  src/component/signup/IdInput.jsx
  src/component/signup/NickNameInput.jsx
  src/component/signup/ownerSignUp/EmailSelector.jsx
  src/component/signup/ownerSignUp/OwnerSignUpInputs.jsx
  src/pages/OwnerSignupPage.jsx
  src/routes/Router.jsx
Labels: ✨feature

#50 [1/n - 19] 로그인 페이지 oAuth API 통신 구현
  package-lock.json
  package.json
  public/google_btn.png
  public/naver_btn.png
  src/component/login/googleButton.jsx
  src/component/login/kakaoButton.jsx
  src/component/login/loginForm.jsx
  src/component/login/naverButton.jsx
  src/index.js
  src/pages/oauthGoogle.jsx
  src/pages/oauthKakao.jsx
  src/pages/oauthNaver.jsx
  src/routes/Router.jsx
Labels: ✨feature

#53 [1/n - 21] 회원가입페이지 oauth 구현
  src/component/signup/IdInput.jsx
  src/component/signup/NickNameInput.jsx
  src/component/signup/SignUpInputs.jsx
  src/pages/BeforeSignUpPage.jsx
  src/pages/SignUpPage.jsx
  src/pages/oauthGoogle.jsx
  src/pages/oauthKakao.jsx
  src/pages/oauthNaver.jsx
  src/recoil/oauthData/atom.js
  src/routes/Router.jsx
Labels: ✨feature

#54 [1/n - 22] JWT 토큰 유효에 따른 마이페이지 버튼 기능 변경
  src/component/Header/Icons.jsx
  src/recoil/isLogin/atom.js
Labels: ✨feature

#57 [1/n - 11] 채팅방 웹 소켓 통신 구현
  package-lock.json
  package.json
  src/component/Header/Icon.jsx
  src/component/chat/ChatBubble.jsx
  src/component/chat/ChatBubbleWrapper.jsx
  src/component/chat/ChatRoom.jsx
  src/component/chat/Chatting.jsx
  src/component/chat/ChattingInput.jsx
Labels: ✨feature

#58 [1/n-20] 방 만들기 페이지 구현
  src/component/createRoom/createRoomPopup.jsx
  src/component/createRoom/menuEntry.jsx
  src/component/createRoom/restaurantList.jsx
  src/component/createRoom/restaurantSearch.jsx
  src/component/createRoom/selectedMenu.jsx
  src/locData.js
  src/pages/createRoom.jsx
  src/recoil/createroomData/atom.js
  src/routes/Router.jsx
  src/scroll.css
Labels: ✨feature

#61 [1/n - 25] 일반 로그인 구현 및 oauth API 업데이트
  package-lock.json
  src/component/login/idInput.jsx
  src/component/login/loginForm.jsx
  src/component/login/pwInput.jsx
  src/pages/oauthGoogle.jsx
  src/pages/oauthKakao.jsx
  src/pages/oauthNaver.jsx
  src/recoil/loginData/atom.js
Labels: 🐛 bug, ✨feature

#62 [1/n - 13 ] 아이디/비밀번호 찾기 결과 페이지 생성
  public/check.png
  src/component/find/findIdForm.jsx
  src/component/find/findPwForm.jsx
  src/component/find/showId.jsx
  src/component/find/showPw.jsx
  src/pages/findIdPage.jsx
  src/pages/findPwPage.jsx
Labels: ✨feature

#65 [1/n - 23] 닉네임 중복 처리 관련 오류
  src/component/signup/NickNameInput.jsx
  src/component/signup/SignUpInputs.jsx
Labels: 🐛 bug

#64 [1/n - 24] History page 서버 API 연결
  src/component/common/UserStateTag.jsx
  src/component/history/HistoryDetailInfoTab.jsx
  src/component/history/HistoryListContainer.jsx
  src/component/history/HistoryListHeader.jsx
  src/component/history/HistoryOrderList.jsx
  src/component/history/HistoryPopup.jsx
  src/component/history/HistoryTab.jsx
  src/component/history/tab/HistoryDetailInfoTable.jsx
  src/component/history/tab/HistoryOrderList.jsx
  src/component/history/tab/HistoryPartyList.jsx
  src/component/history/tab/HistoryTab.jsx
  src/recoil/historyData/atom.js
  src/routes/Router.jsx
Labels: ✨feature

#67 [1/n - 27] 채팅방 API 연결
  src/component/chat/ChatRoom.jsx
  src/component/chat/ChatRoomHeader.jsx
  src/component/chat/ChatRoomInfoDiv.jsx
  src/component/chat/ChatRoomsInfo.jsx
  src/component/chat/Chatting.jsx
  src/component/chat/ChattingInput.jsx
  src/recoil/chatData/atom.js
  src/routes/Router.jsx
Labels: ✨feature

#73 [1/n - 32] 상수 관리 컴포넌트 작성
  src/component/Header/Header.jsx
  src/component/chat/ChatBubble.jsx
  src/component/common/UserStateTag.jsx
  src/constants/colors.js
  src/constants/states.js
Labels: ✨feature, ♻️ refactor

#74 [1/n - 31] 회원 회원가입 메일 인증 기능 구현
  src/component/common/Loading.jsx
  src/component/signup/IdInput.jsx
  src/component/signup/SignUpInputs.jsx
  src/recoil/loading/atom.js
Labels: ✨feature

#76 [1/n - 33] 방장 채팅방 상태 변경 기능
  src/component/chat/ChatRoom.jsx
  src/component/chat/ChatRoomHeader.jsx
  src/component/chat/ChatRoomsInfo.jsx
  src/component/common/StateChanger.jsx
  src/component/history/HistoryListContainer.jsx
  src/component/history/HistoryListHeader.jsx
  src/component/history/HistoryPopup.jsx
  src/component/history/tab/HistoryDetailInfoTable.jsx
  src/component/history/tab/HistoryOrderList.jsx
  src/component/history/tab/HistoryPartyList.jsx
  src/component/history/tab/HistoryTab.jsx
  src/constants/colors.js
  src/pages/HistoryPage.jsx
  src/recoil/historyData/atom.js
Labels: ✨feature

#80 [1/n - 34] 히스토리 팝업에 데이터 전달 안되는 문제 해결
  src/component/history/HistoryListHeader.jsx
Labels: 🐛 bug

#79 [1/n - 35] 채팅 목록 클릭 시 채팅방 헤더에 정보 안 나타나는 문제 해결
  src/component/chat/ChatRoom.jsx
Labels: 🐛 bug

#82 [1/n - 36] 제안서 수락, 거절 기능 구현
  src/component/common/StateChanger.jsx
  src/component/common/icons/TriangleArrow.jsx
  src/component/history/HistoryListHeader.jsx
  src/component/history/tab/HistoryPartyList.jsx
  src/component/history/tab/HistoryReqLi.jsx
  src/recoil/historyData/atom.js
Labels: ✨feature
