Repository 1-n-Fee/1-n-Web-Frontend, pull requests merged in 2022-09, with the labels that each got.

#84 [1/n - 37] 사업자 가게 등록 페이지 구현
  package-lock.json
  package.json
  src/component/common/icons/PlusIcon.jsx
  src/component/manager/AddressInput.jsx
  src/component/manager/home/StoreInfo.jsx
  src/component/manager/storeRegister/CategorySelector.jsx
  src/component/manager/storeRegister/Menu.jsx
  src/component/manager/storeRegister/MenuInput.jsx
  src/component/manager/storeRegister/MoneyInput.jsx
  src/component/manager/storeRegister/RegisterInputs.jsx
  src/component/manager/storeRegister/StoreNameInput.jsx
  src/component/manager/storeRegister/Thumbnail.jsx
  src/component/manager/storeRegister/TimeInput.jsx
  src/component/signup/PhoneNumInput.jsx
  src/constants/arrays.js
  src/pages/manager/ManagerHomePage.jsx
  src/pages/manager/StoreRegisterPage.jsx
  src/routes/Router.jsx
Labels: ✨feature

#87 [1/n - 38] 로그인 페이지 => 회원가입 페이지로 이동 구현
  src/component/login/loginForm.jsx
Labels: ✨feature

#89 [1/n - 40] 회원가입방식 선택 페이지 스타일 수정
  public/googleIcon.png
  public/kakaoIcon.png
  public/naverIcon.png
  src/component/common/Underline.jsx
  src/component/login/CustomOauthBtn.jsx
  src/component/login/googleButton.jsx
  src/component/login/kakaoButton.jsx
  src/component/login/naverButton.jsx
  src/constants/colors.js
  src/pages/BeforeSignUpPage.jsx
Labels: 🎨 style

#90 [1/n - 26] Home 페이지 API 통신 구현
  src/component/home/map.jsx
  src/component/home/meal_detail.jsx
  src/component/home/meal_item.jsx
  src/component/home/meal_list.jsx
  src/component/home/sideBar.jsx
  src/pages/home.jsx
  src/recoil/meal/atom.js
Labels: ✨feature

#93 [1/n - 41] 카카오 지도 SDK 리팩토링
  .env
  .gitignore
  package-lock.json
  package.json
  public/index.html
Labels: ♻️ refactor

#94 [1/n - 39] 회원가입 페이지 -> 사업자 회원가입으로 이동하는 링크 구현
  src/pages/BeforeSignUpPage.jsx
Labels: ✨feature

#99 [1/n - 43] 히스토리 페이지 스타일 수정
  src/component/history/HistoryListContainer.jsx
  src/component/history/HistoryListHeader.jsx
  src/component/history/HistoryPopup.jsx
  src/component/history/tab/HistoryDetailInfoTable.jsx
  src/component/history/tab/HistoryOrderList.jsx
  src/component/history/tab/HistoryPartyList.jsx
  src/component/history/tab/HistoryReqLi.jsx
  src/component/history/tab/HistoryTab.jsx
  src/pages/HistoryPage.jsx
Labels: 🎨 style

#102 [1/n - 45] 사업자 페이지 라우팅 수정
  src/App.js
  src/component/Header/Icons.jsx
  src/component/login/loginForm.jsx
  src/constants/role.js
  src/pages/manager/ManagerHomePage.jsx
  src/recoil/isLogin/atom.js
  src/routes/ManagerRouter.jsx
  src/routes/Router.jsx
Labels: 🐛 bug, ✨feature

#104 [1/n - 47] 사업자 회원가입 오류 해결
  src/component/signup/IdInput.jsx
  src/component/signup/ownerSignUp/OwnerSignUpInputs.jsx
  src/constants/accountType.js
Labels: 🐛 bug

#105 [1/n - 44] home 페이지 사이드바 댓글 기능 추가
  src/component/home/meal_detail.jsx
  src/component/home/meal_item.jsx
  src/pages/home.jsx
  src/recoil/meal/atom.js
Labels: ✨feature

#106 [1/n - 46] 사업자 페이지 스타일 수정
  src/component/Header/Icons.jsx
  src/component/Header/ManagerHeader.jsx
  src/component/style/SignUpStyle.jsx
  src/pages/manager/ManagerHomePage.jsx
  src/recoil/isLogin/atom.js
  src/routes/ManagerRouter.jsx
Labels: 🎨 style

#109 [1/n - 49] 로고 추가
  public/logo.png
  src/component/Header/Header.jsx
Labels: ✨feature

#114 [1/n - 50] 채팅 페이지 스타일 수정
  src/component/chat/ChatRoom.jsx
  src/component/chat/ChatRoomHeader.jsx
  src/component/chat/ChatRoomInfoDiv.jsx
  src/constants/colors.js
Labels: 🎨 style

#113 [1/n - 46] 사업자 페이지 스타일 수정
  public/managerLogo.png
  src/component/Header/ManagerHeader.jsx
  src/component/manager/home/StoreInfo.jsx
  src/component/manager/storeRegister/AddressInput.jsx
  src/component/manager/storeRegister/Menu.jsx
  src/component/manager/storeRegister/MenuInput.jsx
  src/component/manager/storeRegister/MoneyInput.jsx
  src/component/manager/storeRegister/RegisterInputs.jsx
  src/component/manager/storeRegister/StoreNameInput.jsx
  src/component/manager/storeRegister/Thumbnail.jsx
  src/component/manager/storeRegister/TimeInput.jsx
  src/constants/arrays.js
  src/pages/manager/ManagerHomePage.jsx
  src/pages/manager/StoreRegisterPage.jsx
  src/recoil/managerStoreData/atom.js
Labels: ✨feature, 🎨 style

#116 [1/n - 52] 학생 google OAuth 로그인 오류
  src/pages/oauthGoogle.jsx
  src/recoil/loginAndRole/atom.js
Labels: 🐛 bug

#118 [1/n - 53] 로그인 여부 판단하는 atom 변경된 것 - 타 컴포넌트에 반영
  src/component/Header/Icons.jsx
  src/component/signup/SignUpInputs.jsx
  src/pages/oauthKakao.jsx
  src/pages/oauthNaver.jsx
Labels: ♻️ refactor

#120 [1/n - 54] 로그인 여부 판단 atom 파일 이름변경 -> 반영 안된 컴포넌트에서 import 오류
  src/App.js
  src/component/Header/ManagerHeader.jsx
Labels: 🐛 bug

#121 [1/n - 30] 로그아웃 기능 구현
  src/component/Header/MyPageMenu.jsx
Labels: ✨feature

#122 [1/n - 29] 헤더 드롭다운 메뉴 기능 수정
  src/App.js
  src/component/Header/Icons.jsx
  src/component/Header/MyPageMenu.jsx
  src/recoil/menu/atom.js
Labels: ✨feature

#128 [1/n - 55] 히스토리 팝업 - 참여자 메뉴 정보 보여주는 방식 수정
  src/component/history/HistoryListHeader.jsx
  src/component/history/tab/HistoryOrderList.jsx
  src/component/history/tab/HistoryPartyList.jsx
Labels: ✨feature

#130 [1/n - 60] 채팅페이지에서 서버로 무한 요청하는 문제
  src/component/chat/ChatRoomsInfo.jsx
Labels: 🐛 bug

#134 [1/n- 62] 학생 Oauth 회원가입 안되는 문제
  src/component/login/googleButton.jsx
  src/component/login/kakaoButton.jsx
  src/component/login/naverButton.jsx
  src/component/signup/IdInput.jsx
  src/pages/oauthGoogle.jsx
  src/pages/oauthKakao.jsx
  src/pages/oauthNaver.jsx
Labels: 🐛 bug

#136 [1/n - 51] 회원가입 이메일 인증 오류
  src/component/signup/IdInput.jsx
Labels: 🐛 bug, 🎨 style

#137 [1/n - 56] 비로그인으로 접근 불가능한 페이지에 접근 되는 문제 해결
  src/component/Header/Icons.jsx
Labels: 🐛 bug

#146 [1/n - 66] 홈 페이지 사이드바 방 상태 UI 구현
  src/component/Header/SearchItem.jsx
  src/component/history/RequestStateTag.jsx
  src/component/home/meal_item.jsx
Labels: ✨feature, 🎨 style

#147 [1/n - 63] 채팅방 UI 하단 공백 수정
  src/component/chat/ChatRoom.jsx
  src/component/chat/Chatting.jsx
  src/pages/chat/ChatPage.jsx
Labels: 🎨 style

#148 [1/n - 61] 다른 채팅방 내용이 그대로 유지되는 현상 해결
  src/component/chat/Chatting.jsx
Labels: 🐛 bug

#150 [1/n - 67] 헤더 검색창 태그 필터 기능
  src/component/Header/Header.jsx
  src/component/Header/SearchItem.jsx
  src/component/home/DetailInfo.jsx
  src/component/home/DetailMenu.jsx
  src/component/home/MealDetailFooter.jsx
  src/component/home/meal_detail.jsx
  src/component/home/meal_item.jsx
  src/component/home/meal_list.jsx
  src/component/home/sideBar.jsx
  src/pages/home.jsx
  src/recoil/comment/atom.js
  src/recoil/meal/atom.js
Labels: ✨feature

#153 [1/n - 68] merge conflict 해결
  src/component/Header/Header.jsx
  src/component/home/meal_item.jsx
Labels: 🐛 bug

#155 [1/n - 69] menuEntry 이미지 출력 안됨 bug fix
  src/component/createRoom/menuEntry.jsx
Labels: 🐛 bug

#157 [1/n - 70] 이메일 인증 시 오류 문구 출력 안되는 문제
  src/component/signup/IdInput.jsx
  src/component/signup/ownerSignUp/EmailSelector.jsx
Labels: 🐛 bug

#162 [1/n - 72] 채팅 화면에서 다른 화면으로 이동 후 채팅방 재입장시 채팅이 입력되지 않는 문제
  src/component/chat/ChatRoom.jsx
  src/component/chat/Chatting.jsx
  src/component/chat/ChattingInput.jsx
Labels: 🐛 bug

#163 [1/n - 73] 채팅방 기본화면 UI 수정
  src/component/chat/ChatRoom.jsx
Labels: 🎨 style
